archives:
-
  format_overrides:
  - goos: windows
    format: zip
before:
  hooks:
    - go mod download
brews:
-
  dependencies:
  - go
  description: Go Panic Check
  folder: Formula
  github:
    owner: bflad
    name: homebrew-tap
  homepage: https://github.com/bflad/gopaniccheck
  install: |
    bin.install "gopaniccheck"
  test: |
    system "#{bin}/gopaniccheck -V"
builds:
-
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - windows
  - linux
  goarch:
  - amd64
  - 386
  ldflags:
  - -s -w -X github.com/bflad/gopaniccheck/version.Version={{.Version}} -X github.com/bflad/gopaniccheck/version.VersionPrerelease= -X github.com/bflad/gopaniccheck/version.GitCommit={{.ShortCommit}}
  main: ./cmd/gopaniccheck
changelog:
  skip: true
dockers:
-
  build_flag_templates:
  - "--label=org.label-schema.schema-version=1.0"
  - "--label=org.label-schema.version={{.Version}}"
  - "--label=org.label-schema.name={{.ProjectName}}"
  image_templates:
  - 'bflad/gopaniccheck:{{ .Version }}'
  - 'bflad/gopaniccheck:{{ .Major }}.{{ .Minor }}'
  - 'bflad/gopaniccheck:latest'
signs:
-
  artifacts: checksum
